// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nspicayatppuushcizba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zcGljYXlhdHBwdXVzaGNpemJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMDc5NTAsImV4cCI6MjA4MTg4Mzk1MH0.S_9D--AMsd_nezz3pBroVfPyu4Ih38Vx70G2L0-UIIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);